import type { Metadata } from 'next';
import '../styles/globals.scss';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { Toaster } from 'sonner';
import ConvexClientProvider from "@/providers/ConvexClientProvider";
export const metadata: Metadata = {
  title: 'latch',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ConvexClientProvider>
            <Toaster position="bottom-center" closeButton />
            {children}
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
