import type { Metadata } from 'next';
import './globals.scss';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { Toaster } from 'sonner';
export const metadata: Metadata = {
  title: 'latch',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Toaster position="bottom-center" closeButton />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
